version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src  # Only mount src for live reload
      - /app/node_modules  # Prevent overwriting installed node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    command: ["npm", "run", "dev"]  # Run in dev mode with Nodemon

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
