version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Mount project folder to enable live reload
      - /app/node_modules  # Avoid overwriting node_modules
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/mydatabase"
    working_dir: /app/src
    command: ["npm", "run", "dev"]  # Runs Nodemon inside the container

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
