version: "3.8"

services:
  backend:
    image: ghcr.io/rajibmiah/ai-assistant-server:latest
    environment:
      - NODE_ENV=production
      - NEXHEALTH_API_URL=https://nexhealth.info
      - NEXHEALTH_SUBDOMAIN=fomoline-demo-practice-sr8swn
      - NEXHEALTH_API_KEY=dXNlci01Nzgtc2FuZGJveA.gi-wu0zO0mA6K3Ge6TZQqmXzwfPYEErV
      - NEXHEALTH_LOCATION_ID=293267
      
    env_file:
      - .env
    command: ["npm", "run", "start"]  # Run production server

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Read-only nginx config
