version: "3.8"

services:
  backend:
    build: .
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: ["npm", "run", "start"]  # Run production server

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Read-only nginx config
