services:
  backend:
    build:
      context: . # Ensure Dockerfile exists in the root directory
    image: ghcr.io/rajibmiah/ai-assistant-backend:latest
    container_name: ai-assistant-backend
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - NEXHEALTH_API_URL=https://nexhealth.info
      - NEXHEALTH_SUBDOMAIN=fomoline-demo-practice-sr8swn
      - NEXHEALTH_LOCATION_ID=293267
    env_file:
      - .env
    networks:
      - app-network
    command: [ "npm", "run", "start" ]

  # mongo:
  #   image: mongo:6
  #   container_name: mongo-db
  #   volumes:
  #     - mongo-data:/data/db
  #   networks:
  #     - app-network
  #   healthcheck:
  #     test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
  #     interval: 10s
  #     retries: 5
  #     start_period: 5s


  nginx:
    build:
      context: ./nginx # Ensure that the nginx folder contains a Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - backend # ✅ Updated this line
    networks:
      - app-network

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # - ./nginx/certs:/etc/nginx/certs:ro # Ensure certs exist inside nginx folder
    # command: [ "nginx", "-g", "daemon off;" ]


  certbot:
    image: certbot/certbot
    container_name: certbot
    networks:
      - app-network
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ahmedrajib942@gmail.com -d aiassist.eleveapps.ca --agree-tos
networks:
  app-network:


volumes:
  mongo-data:
